# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f206a8303dbd315afe534c536efaf99e33c41510195a8b144d14a6f102ee853ce26acefacfb239c17a2f57938a489c9be2b6c290021810fad05355d4c13ee75

test:
  secret_key_base: 985a140e332aaf4327e6a613f50090f3b14f391f0eae02c46cd6cba19205be7e5cf73c35c454e5ad3601a95ae83867453647c0645426ab4db69b32dcc6b0e487

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
